sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t jmllerit/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true jmllerit/react-test npm test

after_success:
  - docker build -t jmllerit/multi-client ./client
  - docker build -t jmllerit/multi-nginx ./nginx
  - docker build -t jmllerit/multi-server ./server
  - docker build -t jmllerit/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push jmllerit/multi-client
  - docker push jmllerit/multi-nginx
  - docker push jmllerit/multi-server
  - docker push jmllerit/multi-worker

deploy: 
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-docker"
  env: "Multidocker-env"
  # Use S3 bucket
  bucket_name: "elasticbeanstalk-us-east-2-130186549773"
  bucket_path: "docker-multi"
  on:
      branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY