version: '3'
services: 
    postgres:
        # check hub.docker.com to see image version
        image: 'postgres:latest'
        environment:
            - POSTGRES_PASSWORD=postgres_password
    redis:
        image: 'redis:latest'
    nginx:
        depends_on:
            - api
            - client
        restart: always
        build:
            dockerfile: Dockerfile.dev
            context: ./nginx
        ports: 
            - '3050:80'
    api:
        build:
            # File to run
            dockerfile: Dockerfile.dev
            # Directory file of server to buld
            context: ./server
        # volumes to setup 
        # bookmark of the app
        volumes:
            # bookmark this
            - /app/node_modules
            # copy all files from server directory to app directory
            - ./server:/app
        # Configuration variables
        environment: 
            # URL
            - REDIS_HOST=redis
            # PORT - check documentation on docker hub to check default port  (EXPOSE 6379)
            - REDIS_PORT=6379
            - PGUSER=postgres
            - PGHOST=postgres
            - PGDATABASE=postgres
            - PGPASSWORD=postgres_password
            - PGPORT=5432
    client:
        stdin_open: true
        build: 
            dockerfile: Dockerfile.dev
            context: ./client
        volumes:
            - /app/node_modules
            - ./client:/app
    worker:
        build: 
            dockerfile: Dockerfile.dev
            context: ./worker
        volumes:
            - /app/node_modules
            - ./worker:/app
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379